version: "3.9"

services:
  fin_api:
    image: postgres
    container_name: fin_api
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: tests_challenge
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/app
    links: 
      - fin_api
    depends_on:
      - fin_api

volumes:
  pgdata:
    driver: local